[versions]
agp = "8.13.0"
appcompat = "1.7.1"
assetDelivery = "2.3.0"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
converterGson = "3.0.0"
coreSplashscreen = "1.2.0"
datastorePreferences = "1.1.7"
featureDelivery = "2.1.0"
hiltAndroid = "2.57.2"
hiltAndroidCompiler = "2.57.2"
hiltAndroidTesting = "2.57.2"
hiltCompiler = "2.57.2"
hiltCompilerVersion = "2.57.2"
hiltNavigationCompose = "1.3.0"
iconsLucide = "1.1.0"
integrity = "1.5.0"
junitJunit = "4.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinTestJunit5 = "2.2.0"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
composeMaterial = "1.5.5"
junitJupiter = "6.0.1"
mockitoCore = "5.20.0"
mockitoJunitJupiter = "5.20.0"
navigationCompose = "2.9.6"
navigationTesting = "2.9.6"
okhttp = "5.3.0"
pagingCommon = "3.3.6"
pagingCompose = "3.3.6"
pagingRuntime = "3.3.6"
pagingTesting = "3.3.6"
retrofit = "3.0.0"
review = "2.0.2"
reviewKtx = "2.0.2"
robolectric = "4.16"
roomCompiler = "2.8.3"
roomKtx = "2.8.3"
roomPaging = "2.8.3"
roomRuntime = "2.8.3"
runtimeTracing = "1.9.4"
securityCrypto = "1.1.0"
turbine = "1.2.1"
uiTextGoogleFonts = "1.9.4"
workRuntimeKtx = "2.11.0"
workTesting = "2.11.0"
appUpdate = "2.1.0"


[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-paging-testing = { module = "androidx.paging:paging-testing", version.ref = "pagingTesting" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtimeTracing" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
asset-delivery = { module = "com.google.android.play:asset-delivery", version.ref = "assetDelivery" }
asset-delivery-ktx = { module = "com.google.android.play:asset-delivery-ktx", version.ref = "assetDelivery" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil3-coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompilerVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
feature-delivery = { module = "com.google.android.play:feature-delivery", version.ref = "featureDelivery" }
feature-delivery-ktx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "featureDelivery" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
icons-lucide = { module = "com.composables:icons-lucide", version.ref = "iconsLucide" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
junit = { module = "junit:junit", version.ref = "junitJunit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlinTestJunit5" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoJunitJupiter" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingCommon" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review = { module = "com.google.android.play:review", version.ref = "review" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
app-update = { group = "com.google.android.play", name = "app-update", version.ref = "appUpdate" }
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdate" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.21" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

